let members=[], memories=[], timeline=[], game=null;
const $=s=>document.querySelector(s), tokenKey='han_thien_token';
const getToken=()=>localStorage.getItem(tokenKey);
const authHeaders=()=>getToken()?{'Authorization':'Bearer '+getToken(),'Content-Type':'application/json'}:{'Content-Type':'application/json'};
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...authHeaders(),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Có lỗi xảy ra.');return d}
async function loadData(){try{const d=await api('/api/data');members=d.members;memories=d.memories;timeline=d.timeline;$('#memberCount').textContent=members.length;$('#memoryCount').textContent=memories.length;renderMembers();renderGallery();renderTimeline();}catch(e){console.error(e)}}
function renderMembers(list=members){$('#membersGrid').innerHTML=list.length?list.map(m=>`<article class="member-card" data-index="${members.indexOf(m)}"><div class="avatar">${m.emoji}</div><div class="member-info"><span class="nickname">${m.nick}</span><h3>${m.name}</h3><p>${m.role}</p><div class="tags">${m.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div></article>`).join(''):`<p>Không tìm thấy môn nhân phù hợp.</p>`;document.querySelectorAll('.member-card').forEach(c=>c.onclick=()=>openMember(+c.dataset.index))}
function renderGallery(){$('#galleryGrid').innerHTML=memories.map(m=>`<article class="memory"><div class="pic">${m.icon}</div><div class="caption">${m.title}<small>${m.description}</small></div></article>`).join('')}
function renderTimeline(){$('#timelineList').innerHTML=timeline.map(e=>`<article class="event"><i class="dot"></i><span class="date">${e.year}</span><h3>${e.title}</h3><p>${e.description}</p></article>`).join('')}
function openMember(i){const m=members[i];$('#modalContent').innerHTML=`<div class="modal-avatar">${m.emoji}</div><div class="modal-content"><span class="nickname">${m.nick}</span><h2>${m.name}</h2><p>${m.bio}</p><div class="facts"><div class="fact"><small>Sinh nhật</small><b>${m.birthday||'—'}</b></div><div class="fact"><small>Sở thích</small><b>${m.hobby||'—'}</b></div></div><div class="tags">${m.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div>`;$('#memberModal').showModal()}
function accountUI(user){if(user){$('#userBadge').textContent='☯ '+user.displayName;$('#userBadge').classList.remove('hidden');$('#accountBtn').textContent='Hồ sơ'}else{$('#userBadge').classList.add('hidden');$('#accountBtn').textContent='☯ Đăng nhập'}}
async function checkSession(){if(!getToken()){accountUI(null);return}try{const d=await api('/api/me');accountUI(d.user);await loadGame()}catch{localStorage.removeItem(tokenKey);accountUI(null)}}
function openAccount(){if(getToken())showProfile();else renderAuth('login')}
async function showProfile(){try{const d=await api('/api/me'),s=d.state,p=s.profile,r=s.realm;$('#accountContent').innerHTML=`<div class="account-box"><div class="avatar-mini">🧙‍♂️</div><span class="eyebrow">ĐÃ NHẬP MÔN</span><h3>${d.user.displayName}</h3><p>Đạo hiệu: <b>${d.user.username}</b></p><p>Cảnh giới: <b>${r.name}</b> · Linh lực: <b>${p.spirit_power}</b></p><p>Linh thạch: <b>💠 ${p.spirit_stones}</b></p><p>Quyền hạn: ${r.permission}</p><button id="logoutBtn" class="btn logout">Rời phiên đăng nhập</button></div>`;$('#accountModal').showModal();$('#logoutBtn').onclick=logout}catch(e){renderAuth('login')}}
function renderAuth(mode){const register=mode==='register';$('#accountContent').innerHTML=`<div class="auth-title">寒天門</div><div class="auth-sub">Ghi danh môn nhân · Dữ liệu được lưu trong PostgreSQL</div><div class="tabs"><button class="tab ${!register?'active':''}" data-mode="login">Đăng nhập</button><button class="tab ${register?'active':''}" data-mode="register">Đăng ký</button></div><form id="authForm" class="auth-form"><div class="field ${register?'':'hidden'}"><label>Danh xưng</label><input id="displayName" maxlength="40" ${register?'required':''} placeholder="Tên hiển thị"></div><div class="field"><label>Tên tài khoản</label><input id="username" required minlength="3" maxlength="24" autocomplete="username" placeholder="tu_tien_01"></div><div class="field"><label>Mật khẩu</label><input id="password" type="password" required minlength="6" autocomplete="current-password" placeholder="Ít nhất 6 ký tự"></div><button class="btn primary" type="submit">${register?'Ghi danh vào sơn môn':'Nhập môn'}</button><div id="authMsg" class="auth-msg"></div></form>`;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>renderAuth(b.dataset.mode));$('#authForm').onsubmit=async e=>{e.preventDefault();const msg=$('#authMsg');msg.textContent='Đang xử lý...';const body={username:$('#username').value.trim(),password:$('#password').value};if(register)body.displayName=$('#displayName').value.trim();try{const d=await api(register?'/api/register':'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(register){msg.textContent='Ghi danh thành công. Đang chuyển sang đăng nhập...';setTimeout(()=>renderAuth('login'),500)}else{localStorage.setItem(tokenKey,d.token);accountUI(d.user);$('#accountModal').close();await loadGame()}}catch(err){msg.textContent=err.message}};$('#accountModal').showModal()}
async function logout(){try{await api('/api/logout',{method:'POST'})}finally{localStorage.removeItem(tokenKey);accountUI(null);$('#accountModal').close();renderLoggedOut()}}
function renderLoggedOut(){['#cultivationPanel','#missionGrid','#caveGrid','#shopGrid','#beastGrid','#chatList','#leaderboard'].forEach(s=>{const el=$(s);if(el)el.innerHTML='<div class="empty-state">Đăng nhập để bước vào đạo trường.</div>'})}
async function loadGame(){if(!getToken()){renderLoggedOut();return}try{game=await api('/api/game');renderGame()}catch(e){if(e.message.includes('đăng nhập')){localStorage.removeItem(tokenKey);accountUI(null);renderLoggedOut()}}}
function renderGame(){const s=game.state,p=s.profile,r=s.realm,prev=game.realms[r.tier-1],next=game.realms[r.tier]||null;const max=next?next.need:Math.max(p.spirit_power,3500),base=prev.need,percent=next?Math.min(100,Math.max(0,(p.spirit_power-base)/(next.need-base)*100)):100;$('#cultivationPanel').innerHTML=`<div class="cultivation-card"><div class="cultivation-top"><div><span class="eyebrow">CẢNH GIỚI HIỆN TẠI</span><div class="realm-name">${r.name}</div><p class="muted">${r.permission}</p></div><div><span class="eyebrow">LINH LỰC</span><div class="power">${p.spirit_power}</div></div></div><div class="progress"><i style="width:${percent}%"></i></div><p class="muted">${next?`Còn ${Math.max(0,next.need-p.spirit_power)} linh lực để đột phá ${next.name}.`:'Đã đạt Cửu Tầng — cảnh giới tối cao của sơn môn.'}</p><div class="mini-grid"><div class="mini-stat"><small>Tu luyện hôm nay</small><b>${p.daily_cultivations}/6</b></div><div class="mini-stat"><small>Linh thạch</small><b>💠 ${p.spirit_stones}</b></div><div class="mini-stat"><small>Chiến thắng</small><b>${p.challenge_wins}</b></div></div><button id="cultivateBtn" class="btn primary" style="margin-top:18px;width:100%">🧘 Vận công</button><div id="cultivateMsg" class="result-msg"></div></div><div class="permission-card"><span class="eyebrow">QUYỀN HẠN CỬU TẦNG</span><div class="permission-list">${game.realms.map(x=>`<div class="permission ${x.tier>r.tier?'locked':''}"><span>${x.name}</span><b>${x.tier<=r.tier?'✓ '+x.permission:'🔒'}</b></div>`).join('')}</div></div>`;$('#cultivateBtn').onclick=async()=>{try{const d=await api('/api/cultivate',{method:'POST'});game.state=d.state;renderGame();$('#cultivateMsg').textContent=d.message}catch(e){$('#cultivateMsg').textContent=e.message}};
 renderMissions();renderCaves();renderShop();renderBeasts();renderChat();renderLeaderboard();}
function renderMissions(){$('#missionGrid').innerHTML=game.missions.map(m=>`<article class="game-card"><div class="game-icon">${m.icon}</div><h3>${m.title}</h3><p>${m.description}</p><div class="game-meta"><span class="chip gold">💠 +${m.spirit_reward}</span><span class="chip">✨ +${m.power_reward} linh lực</span></div><button class="btn ${m.completed?'ghost':'primary'}" data-mission="${m.id}" ${m.completed?'disabled':''}>${m.completed?'✓ Đã hoàn thành':'Nhận nhiệm vụ'}</button></article>`).join('');document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=async()=>{try{const d=await api('/api/missions/'+b.dataset.mission+'/complete',{method:'POST'});alert(d.message);await loadGame()}catch(e){alert(e.message)}})}
const caves=[{name:'Bí Cảnh Thanh Vân',icon:'☁️',min:1,stone:100,power:35,desc:'Bí cảnh sơ cấp, thích hợp cho tân đệ tử.'},{name:'Hàn Nguyệt Động Thiên',icon:'🌙',min:4,stone:220,power:70,desc:'Hàn khí dày đặc, chỉ Tứ Tầng trở lên mới chịu được.'},{name:'Cửu U Bí Cảnh',icon:'🌀',min:8,stone:500,power:120,desc:'Thâm uyên nguy hiểm, dành cho Bát Tầng trở lên.'}];
function renderCaves(){$('#caveGrid').innerHTML=caves.map(c=>{const ok=game.state.profile.tier>=c.min;return `<article class="game-card"><div class="game-icon">${c.icon}</div><h3>${c.name}</h3><p>${c.desc}</p><div class="game-meta"><span class="chip gold">💠 +${c.stone}</span><span class="chip">✨ +${c.power}</span><span class="chip">${game.realms[c.min-1].name}</span></div><button class="btn ${ok?'primary':'ghost'}" data-cave="${c.name}" ${ok?'':'disabled'}>${ok?'◈ Nhập bí cảnh':'🔒 Chưa đủ cảnh giới'}</button></article>`}).join('');document.querySelectorAll('[data-cave]').forEach(b=>b.onclick=async()=>{try{const d=await api('/api/cave',{method:'POST',body:JSON.stringify({name:b.dataset.cave})});alert(d.message);await loadGame()}catch(e){alert(e.message)}})}
function renderShop(){$('#shopGrid').innerHTML=game.shop.map(i=>{const ok=game.state.profile.tier>=i.min_tier;return `<article class="game-card"><div class="game-icon">${i.icon}</div><h3>${i.name}</h3><p>${i.description}</p><div class="game-meta"><span class="chip gold">💠 ${i.price}</span><span class="chip">${game.realms[i.min_tier-1].name}</span></div><button class="btn ${ok?'primary':'ghost'}" data-buy="${i.id}" ${ok?'':'disabled'}>${ok?'Mua vật phẩm':'🔒 Chưa đủ cảnh giới'}</button></article>`}).join('');document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=async()=>{try{const d=await api('/api/shop/buy',{method:'POST',body:JSON.stringify({itemId:Number(b.dataset.buy)})});alert(d.message);await loadGame()}catch(e){alert(e.message)}})}
function renderBeasts(){$('#beastGrid').innerHTML=game.beasts.map(b=>{const ok=game.state.profile.tier>=b.min_tier;const owned=game.state.beasts.some(x=>x.name===b.name);return `<article class="game-card"><div class="game-icon">${b.icon}</div><h3>${b.name}</h3><p>${b.description}</p><div class="game-meta"><span class="chip gold">💠 ${b.price}</span><span class="chip">${game.realms[b.min_tier-1].name}</span></div><button class="btn ${owned?'ghost':ok?'primary':'ghost'}" data-beast="${b.id}" ${owned||!ok?'disabled':''}>${owned?'✓ Đã thu phục':ok?'Thu phục':'🔒 Chưa đủ cảnh giới'}</button></article>`}).join('');document.querySelectorAll('[data-beast]').forEach(b=>b.onclick=async()=>{try{const d=await api('/api/beasts/buy',{method:'POST',body:JSON.stringify({beastId:Number(b.dataset.beast)})});alert(d.message);await loadGame()}catch(e){alert(e.message)}})}
function renderChat(){if(!getToken()){renderLoggedOut();return}$('#chatList').innerHTML=game.chat.length?game.chat.map(m=>`<div class="chat-msg"><b>${m.display_name}</b><small> · ${new Date(m.created_at).toLocaleString('vi-VN')}</small><p>${escapeHtml(m.message)}</p></div>`).join(''):'<p class="muted">Sơn môn còn tĩnh lặng. Hãy truyền âm đầu tiên.</p>';$('#chatList').scrollTop=$('#chatList').scrollHeight}
function renderLeaderboard(){$('#leaderboard').innerHTML=game.leaderboard.length?game.leaderboard.map((x,i)=>`<div class="rank-row"><span class="r">${i+1}</span><div><b>${escapeHtml(x.display_name)}</b><small>${game.realms[x.tier-1]?.name||'Nhất Tầng'} · ${x.spirit_power} linh lực</small></div><strong>💠 ${x.spirit_stones}</strong></div>`).join(''):'<p class="muted">Chưa có đệ tử trên bảng.</p>'}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#chatForm').onsubmit=async e=>{e.preventDefault();if(!getToken()){alert('Hãy đăng nhập trước.');return}const input=$('#chatInput');const msg=input.value.trim();if(!msg)return;try{const d=await api('/api/chat',{method:'POST',body:JSON.stringify({message:msg})});game.chat=d.chat;input.value='';renderChat()}catch(err){alert(err.message)}};
$('#challengeBtn').onclick=async()=>{try{const d=await api('/api/challenge',{method:'POST',body:JSON.stringify({enemyPower:Number($('#enemyPower').textContent)})});$('#challengeMsg').textContent=d.message;game.state=d.state;renderGame()}catch(e){$('#challengeMsg').textContent=e.message}};
$('#searchInput').oninput=e=>{const q=e.target.value.toLowerCase().trim();renderMembers(members.filter(m=>[m.name,m.nick,m.role,...m.tags].join(' ').toLowerCase().includes(q)))};
$('#accountBtn').onclick=openAccount;$('#joinBtn').onclick=()=>getToken()?showProfile():renderAuth('register');$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');const dark=document.body.classList.contains('dark');$('#themeBtn').textContent=dark?'☀':'☾';localStorage.setItem('theme',dark?'dark':'light')};$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));$('#topBtn').onclick=()=>scrollTo({top:0,behavior:'smooth'});$('#modalClose').onclick=()=>$('#memberModal').close();$('#accountClose').onclick=()=>$('#accountModal').close();$('#memberModal').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.close()};$('#accountModal').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.close()};
if(localStorage.getItem('theme')==='dark'){document.body.classList.add('dark');$('#themeBtn').textContent='☀'}loadData();checkSession();
